### ISSUE TITLE
Unable to retrieve Ledger Entries nor Order History

### ISSUE THREAD

**Issue by DaMaddCyantist** [thomasbeukema/cobinhood_api#1]
Hey Thomas,

I've been using your wrapper for about a month.
It is a great piece of work. Thank you for your contribution.

I am trying to extract my ledger entries / order history in order to keep track of my trades,
however, I keep receiving an error when executing either method.

When executing the 'get_ledger_entries' method, I receive: 
TypeError: 'Response' object is not subscriptable

When executing the 'get_order_history' method, I receive:
TypeError: 'Response' object is not subscriptable

Have you had this issue ?
Please, look into this and let me know.

Thank you.

**Comment by thomasbeukema** [comment]
Hi,

I looked into this and it turned out to be a typo. I fixed this, so I'll close this issue.

**Comment by DaMaddCyantist** [comment]
Hey Thomas,

Still getting the TypeError.

DOUBLE EDIT: 

~~I removed the logic that stated: 'if res['success'] == True...
and I'm simply returning the result (return res) which is giving me a dump of the data.~~

~~I've read that one should try to put the result into a dictionary(?)
Here's the link to what I found:~~

https://stackoverflow.com/questions/34508981/response-object-is-not-subscriptable-python-http-post-request 

Changing the " return res['result'] " lines to " return res["result"] " (double quotes instead of single quotes) is allowing me to pull the ledger entries into a dictionary.

**Comment by thomasbeukema** [comment]
Thanks for coming up with a solution yourself, I'll fix it.
